### ISSUE TITLE
Bug if using if_updated and if_succeeds

### ISSUE THREAD

**Issue by newcodepusher** [ConsenSys/scribble#39]
scribble 0.4.2

``` solidity
pragma solidity >=0.6.0 <0.8.0;

contract Token {
    function balanceOf(address x) external pure returns (uint) {
        return 123;
    }
}

contract Foo {
    /// if_updated tokenBalance == 123;
    uint public tokenBalance = 1;
    
    /// if_succeeds Token(x).balanceOf(address(this)) == 123;
    function updateBalance(address x) public returns (uint) {
        tokenBalance = Token(x).balanceOf(address(this));
        return tokenBalance;
    }
}

```

```
/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/bin/scribble.js:574
            throw e;
            ^

Error: Mismatch in length between [] of len 0 and [Identifier#81] of len 1
    at assert (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/util/misc.js:16:11)
    at Object.zip (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/util/misc.js:194:5)
    at helper (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:99:24)
    at getAssignments (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:204:20)
    at getAssignments.next (<anonymous>)
    at Object.findAliasedStateVars (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:262:21)
    at instrumentFiles (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/bin/scribble.js:165:38)
    at Object.<anonymous> (/.nvm/versions/node/v12.22.1/lib/node_modules/eth-scribble/dist/bin/scribble.js:568:40)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by cd1m0** [comment]
Thank you for reporting this! Looking at it now

**Comment by cd1m0** [comment]
Ok I think I found it. The issue is on this line:

https://github.com/ConsenSys/scribble/blob/6e737c9ff7db2e0466825411b86a810a6079f988/src/instrumenter/transpile.ts#L387

Essentially when transpiling function calls from Scrible -> Solidity we ALWAYS set the kind as `functionCall`. However in the annotation you have: ` /// if_succeeds Token(x).balanceOf(address(this)) == 123;`  `Token(x)` is of kind `typeConversion` not `functionCall`. This confuses some code inside `getAssignments` which is ran after the function is instrumented, but before the state var is instrumented. Should be a fairly easy fix, will add it tomorrow and roll it in the next release. Sorry for the delay.

**Comment by cd1m0** [comment]
Fixed as part of https://github.com/ConsenSys/scribble/pull/41
