### ISSUE TITLE
Scribble fails on ternary operator in tuple assignment

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#62]
```solidity
function f(bool cond) internal pure returns (uint[2] memory ret) {
  (ret[0], ret[1]) = cond ? (1, 2) : (3, 4);
}
```

results in

```
Error: Unexpected rhs in tuple assignment: Conditional#1710
    at getAssignmentComponents (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:41:19)
    at getAssignmentComponents.next (<anonymous>)
    at getAssignments (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:124:20)
    at getAssignments.next (<anonymous>)
    at Object.findAliasedStateVars (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:272:21)
    at new InstrumentationContext (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/instrumentation_context.js:231:38)
    at Object.<anonymous> (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/bin/scribble.js:582:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by cd1m0** [comment]
Thank you for reporting this! Will take a look and root-cause tomorrow!

**Comment by cd1m0** [comment]
First a bit of context: In order to detect when its safe to instrument state variables (for #if_updated annotations), we need to detect when a state variable may be aliased. To detect that we need to locate all of the places in the AST where the state variable may be assigned to a local/argument/return etc. This is done in `getAssignments`. This logic has to deal with tuple assignments, and so far it has only dealt with simple cases of tuple assignments - tuple to tuple and function call to tuple. It doesn't yet handle assignments where the RHS is a conditional (causing the exception you see).

To fix this, we must first add the following case to `getAssignmentComponents`:

```
--- a/src/instrumenter/state_vars.ts
+++ b/src/instrumenter/state_vars.ts
@@ -72,6 +72,9 @@ function* getAssignmentComponents(lhs: Expression, rhs: Expression): Iterable<[L
 
                 yield [lhsComp, [rhs, i]];
             }
+        } else if (rhs instanceof Conditional) {
+            yield* getAssignmentComponents(lhs, rhs.vTrueExpression);
+            yield* getAssignmentComponents(lhs, rhs.vFalseExpression);
         } else {
             throw new Error(`Unexpected rhs in tuple assignment: ${pp(rhs)}`);
         }
```

And must also modify `explodeTupleAssignment` to correctly handle this tuple case.

**Comment by axic** [comment]
Thanks, this seems to be working with `develop`.
