### ISSUE TITLE
Recursive/cyclic imports are not supported

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#64]
Solidity supports recursive/cyclic imports. We may want to question whether this is good or not, but it is being used.

`A.sol`:
```
import "./B.sol";

interface A {
  function a() external returns (B);
}
```

`B.sol`:
```
import "./A.sol";

interface B {
  function a() external returns (A);
}
```

The error:
```
/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:16
    throw new Error(message);
    ^

Error: Order [[SourceUnit#9,SourceUnit#0],[SourceUnit#0,SourceUnit#9]] is not a valid proper order. Topo sort stalled at 1 out of 3
    at assert (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:16:11)
    at Object.topoSort (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:186:9)
    at sortUnits (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/bin/scribble.js:331:19)
    at Object.<anonymous> (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/bin/scribble.js:611:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by cd1m0** [comment]
Thank you for reporting this! Will take a look and root-cause tomorrow!

**Comment by cd1m0** [comment]
So I misunderstood in my previous comment the problem - this is not actually solved yet, and its a little tricky. This impacts only output in `flat` mode, and to actually solve it we need to change how we do flattening.

I think instead of sorting the units by inclusion order, it might be sufficient to just sort `ContractDefinition`s in topographical order of inheritance, and leave other nodes as they are.

**Comment by axic** [comment]
Thanks, this seems to be working with `develop`.

**Comment by axic** [comment]
@cd1m0 On the same codebase whatever I do (like adding an `invariant` or a `if_succeeds` statement) I keep getting Javascript `Maximum call stack size exceeded` errors.

Two kinds in particular:
1) The first seems to be inside type checking:
```
Internal error in type-checking: Maximum call stack size exceeded
```

2) The seconds seems to be around recursive imports:
```
/Users/alex/Projects/scribble/dist/bin/scribble.js:494
            throw e;
            ^

RangeError: Maximum call stack size exceeded
    at ImportDirective.get vSymbolAliases [as vSymbolAliases] (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/implementation/meta/import_directive.js:55:45)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:101:28)
    at lookupInSourceUnit.next (<anonymous>)
    at new Set (<anonymous>)
    at lookupInScope (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:229:12)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:104:35)
    at lookupInSourceUnit.next (<anonymous>)
    at new Set (<anonymous>)
    at lookupInScope (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:229:12)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:104:35)
```

(It is a local install of 912a472)

I tried for a quite bit of time create a reduced example, but can't really spend too many hours on it. Do you have any idea based on the above?
