### ISSUE TITLE
Javascript call stack exceeded

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#80]
On the same codebase whatever I do (like adding an invariant or a if_succeeds statement) I keep getting Javascript Maximum call stack size exceeded errors.

Two kinds in particular:

1) The first seems to be inside type checking:
```
Internal error in type-checking: Maximum call stack size exceeded
```

2) The seconds seems to be around recursive imports:
```
/Users/alex/Projects/scribble/dist/bin/scribble.js:494
            throw e;
            ^

RangeError: Maximum call stack size exceeded
    at ImportDirective.get vSymbolAliases [as vSymbolAliases] (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/implementation/meta/import_directive.js:55:45)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:101:28)
    at lookupInSourceUnit.next (<anonymous>)
    at new Set (<anonymous>)
    at lookupInScope (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:229:12)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:104:35)
    at lookupInSourceUnit.next (<anonymous>)
    at new Set (<anonymous>)
    at lookupInScope (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:229:12)
    at lookupInSourceUnit (/Users/alex/Projects/scribble/node_modules/solc-typed-ast/dist/ast/definitions.js:104:35)
```

(It is a local install of 912a472)

I think the second case may be connected to #64.

I tried for a quite bit of time create a reduced example, but can't really spend too many hours on it. @cd1m0 do you have any idea based on the above?

**Comment by cd1m0** [comment]
@axic thanks for pointing this out! Do you have a sample/link to a codebase so we can reproduce it too? And yeah, this looks like its related to the fix to #64.

**Comment by axic** [comment]
> Do you have a sample/link to a codebase so we can reproduce it too?

I have tried creating an example a few times, probably spent over an hour on it, but couldn't yet reduce it. I cannot share the source yet :(

**Comment by cd1m0** [comment]
Ok. Will try to look at the code and find anything suspicious

**Comment by cd1m0** [comment]
I was able to reproduce the issue by trying to look-up an identifier that doesn't exist. Here are the samples:
A.sol:
```
import "./B.sol";

/// #invariant dummy > 0;
contract A {
  function a(B arg) external returns (B) {return arg;}
}
```
B.sol:
```
import "./A.sol";

contract B {
  function a(A arg) external returns (A) { return arg; }
}
```

Doing `scribble A.sol` crashes with the same stack trace. The issue however is in solc-typed-ast. Essentially if we don't find a definition for the `dummy` at the root level of `A.sol`, we try looking it up at the root level of `B.sol`, and then we ping-pong back and forth.

**Comment by axic** [comment]
Tried 0.5.7, but it still happens.

The repository however now is public: https://github.com/tempus-finance/tempus-protocol

As an extremely simple example, add `/// #invariant version == 1;` at https://github.com/tempus-finance/tempus-protocol/blob/master/contracts/TempusPool.sol#L22

**Comment by cd1m0** [comment]
@axic thanks for following up! Will reproduce this and try to give you rootcause/fix :)

**Comment by axic** [comment]
@cd1m0 much appreciated, can't wait to create some scribble specifications 😅
