### ISSUE TITLE
Scribble crashes when mixing `for_all` and `if_updated` on nested mappings

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/scribble#88]
Consider the following sample:
```
contract Foo {
    /// #if_updated forall(uint k in m) m[k][0] > 1;
    mapping(uint=>mapping(uint => uint)) m;

    function main() public {
        m[0][1] = 1;
    }
}```

Running scribble 0.5.5 on this sample produces the following crash:

```
/home/dimo/work/consensys/scribble-clean/dist/bin/scribble.js:500
            throw e;
            ^

Error
    at Object.assert (/home/dimo/work/consensys/scribble-clean/dist/util/misc.js:16:11)
    at decomposeLHS (/home/dimo/work/consensys/scribble-clean/dist/instrumenter/state_vars.js:395:9)
    at addStateVarUpdateLocDesc (/home/dimo/work/consensys/scribble-clean/dist/instrumenter/state_vars.js:456:33)
    at Object.findStateVarUpdates (/home/dimo/work/consensys/scribble-clean/dist/instrumenter/state_vars.js:481:13)
    at instrumentFiles (/home/dimo/work/consensys/scribble-clean/dist/bin/scribble.js:204:37)
    at Object.<anonymous> (/home/dimo/work/consensys/scribble-clean/dist/bin/scribble.js:494:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

The issue is that the logic inside `decomposeLHS` is not written to handle functions returning a storage pointer, since scribble doesn't allow instrumenting state variables that are aliased. However the custom mapping instrumentation due to the `forall` introduces a call to `<custom map library>.get_lhs(...)` on the LHS of an assignment. To fix this we need to make `decomposeLHS` aware of potential changes done by the custom map instrumentation.

**Comment by cd1m0** [comment]
Fixed with #90
